"""add_category_notify_chat_ids_task_0043

Revision ID: 6428ace93f06
Revises: a8dc0ce16341
Create Date: 2026-06-03 23:58:50.734268+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6428ace93f06'
down_revision: Union[str, None] = 'a8dc0ce16341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # nullable JSON/Text (список int chat_id), default NULL/пусто (как global_days); TASK-0043
    op.add_column("categories", sa.Column("notify_chat_ids", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'notify_chat_ids')
    # ### end Alembic commands ###
