"""add_wallet_icon_task_0042

Revision ID: a8dc0ce16341
Revises: 1bbc3806ea9e
Create Date: 2026-06-03 23:50:33.689753+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8dc0ce16341'
down_revision: Union[str, None] = '1bbc3806ea9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # nullable + server_default for existing rows compatibility (sqlite/pg); criteria: nullable + default
    op.add_column(
        "wallets",
        sa.Column("icon", sa.String(length=10), nullable=False, server_default="👛"),
    )
    # explicit backfill for safety on dbs without server_default backfill
    op.execute("UPDATE wallets SET icon = '👛' WHERE icon IS NULL OR icon = ''")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'icon')
    # ### end Alembic commands ###
